In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('calibrate2.csv')
df

         gyr_x     gyr_y     gyr_z     acc_x     acc_y     acc_z
0     0.244141 -2.258301 -3.479004 -0.077812 -0.044293 -9.838972
1     0.244141 -2.258301 -3.479004 -0.094571 -0.026336 -9.844957
2     0.244141 -2.197266 -3.356934 -0.095768 -0.038307 -9.846154
3     0.305176 -2.380371 -3.295898 -0.089783 -0.043096 -9.844957
4     0.122070 -2.319336 -3.356934 -0.059855 -0.041899 -9.843761
...        ...       ...       ...       ...       ...       ...
1207  0.305176 -2.258301 -3.417969 -0.069432 -0.035913 -9.849746
1208  0.244141 -2.197266 -3.417969 -0.068235 -0.039504 -9.823410
1209  0.244141 -2.380371 -3.295898 -0.073023 -0.041899 -9.843761
1210  0.305176 -2.319336 -3.356934 -0.075417 -0.043096 -9.815030
1211  0.305176 -2.319336 -3.417969 -0.083797 -0.031125 -9.831789

[1212 rows x 6 columns]

In [6]:
df.describe()

,gyr_x,gyr_y,gyr_z,acc_x,acc_y,acc_z
count,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000
mean,0.290320,-2.301660,-3.402458,-0.067455,-0.038283,-9.838081
std,0.053464,0.052069,0.054165,0.007149,0.005400,0.009495
min,0.122070,-2.441406,-3.540039,-0.138864,-0.053870,-9.861717
25%,0.244141,-2.319336,-3.417969,-0.071826,-0.041899,-9.846154
50%,0.305176,-2.319336,-3.417969,-0.067038,-0.039504,-9.840169
75%,0.305176,-2.258301,-3.356934,-0.063446,-0.035913,-9.831789
max,0.427246,-2.136230,-3.234863,-0.044293,-0.001197,-9.791088

In [12]:
accx = df['acc_x']
type(float(accx.mean()))

float

In [13]:
x = float([df['gyr_x'].mean(), df['gyr_y'].mean()])
type(x)

TypeError: float() argument must be a string or a number, not 'list'